# node-groups defines node groups that can be registered in the cluster
# node-groups may inherit it's configuration from already defined node-group and override specific fields from it
node-groups:
  default:
    _inherit: ""
    image: ethersphere/bee:latest
    image-pull-policy: Always
    ingress-annotations:
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/affinity-mode: "persistent"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
      nginx.ingress.kubernetes.io/session-cookie-max-age: "86400"
      nginx.ingress.kubernetes.io/session-cookie-name: "SWARMGATEWAY"
      nginx.ingress.kubernetes.io/session-cookie-path: "default"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingress-class: "nginx"
    labels:
      app.kubernetes.io/component: "node"
      app.kubernetes.io/name: "bee"
      app.kubernetes.io/part-of: "bee"
      app.kubernetes.io/version: "latest"
      beekeeper.ethswarm.org/node-funder: "true"
    persistence-enabled: false
    persistence-storage-class: "local-storage"
    persistence-storage-request: "34Gi"
    pod-management-policy: "OrderedReady"
    resources-limit-cpu: "1"
    resources-limit-memory: 2Gi
    resources-request-cpu: 750m
    resources-request-memory: 1Gi
    restart-policy: "Always"
    update-strategy: "RollingUpdate"

# bee-configs defines Bee configuration that can be assigned to node-groups
# bee-configs may inherit it's configuration from already defined bee-config and override specific fields from it
bee-configs:
  default:
    _inherit: ""
    allow-private-cidrs: true
    api-addr: ":1633"
    block-time: 1
    blockchain-rpc-endpoint: "ws://geth-swap.bee-playground.svc.swarm1.local:8546"
    bootnode-mode: false
    bootnodes: ""
    cache-capacity: 1000000
    chequebook-enable: true
    cors-allowed-origins: ""
    data-dir: "/home/bee/.bee"
    db-block-cache-capacity: 33554432
    db-disable-seeks-compaction: false
    db-open-files-limit: 200
    db-write-buffer-size: 33554432
    full-node: true
    mainnet: false
    nat-addr: ""
    network-id: 12345
    p2p-addr: ":1634"
    p2p-ws-enable: false
    password: "beekeeper"
    payment-early-percent: 50
    payment-threshold: 13500000
    payment-tolerance-percent: 25
    postage-stamp-address: "0x657241f4494A2F15Ba75346E691d753A978C72Df"
    postage-stamp-start-block: 1
    price-oracle-address: "0x5aFE06fcC0855a76a15c3544b0886EDBE3294d62"
    redistribution-address: "0x09Ad42a7d020244920309FfA14EA376dd2D3b7d5"
    resolver-options: ""
    staking-address: "0xfc28330f1ecE0ef2371B724E0D19c1EE60B728b2"
    storage-incentives-enable: true
    swap-enable: true
    swap-factory-address: "0xdD661f2500bA5831e3d1FEbAc379Ea1bF80773Ac"
    swap-initial-deposit: 500000000000000000
    tracing-enabled: true
    tracing-endpoint: "10.10.11.199:6831"
    tracing-service-name: "bee"
    verbosity: 5 # 1=error, 2=warn, 3=info, 4=debug, 5=trace
    warmup-time: 0s
    welcome-message: "Welcome to the Swarm, you are Bee-ing connected!"
    withdrawal-addresses-whitelist: "0xec44cb15b1b033e74d55ac5d0e24d861bde54532"
  bootnode:
    _inherit: "default"
    bootnode-mode: true
