clusters:
  mainnet-dev-bee-nocheq:
    _inherit: ""
    name: bee
    namespace: dev-bee-perf
    disable-namespace: true
    api-domain: dev-bee-perf.mainnet.internal
    api-domain-internal: dev-bee-perf.svc.godfather2.local:1633
    api-insecure-tls: true
    api-scheme: http
    funding:
      eth: 0.1
      gbzz: 2.0
    node-groups:
      cheq-3-bee:
        mode: node
        bee-config: mainnet-dev-bee-nocheq
        config: mainnet-dev-bee-nocheq
        count: 1
      cheq-4-bee:
        mode: node
        bee-config: mainnet-dev-bee-nocheq
        config: mainnet-dev-bee-nocheq
        count: 1

# node-groups defines node groups that can be registered in the cluster
# node-groups may inherit it's configuration from already defined node-group and override specific fields from it
node-groups:
  mainnet-dev-bee-nocheq:
    _inherit: "default"
    persistence-enabled: true

# bee-configs defines Bee configuration that can be assigned to node-groups
# bee-configs may inherit it's configuration from already defined bee-config and override specific fields from it
bee-configs:
  mainnet-dev-bee-nocheq:
    _inherit: "default"
    bootnodes: "/dnsaddr/mainnet.ethswarm.org"
