clusters:
  mainnet:
    _inherit: ""
    name: bee
    namespace: bee
    disable-namespace: true
    api-domain: internal.ethswarm.org
    api-insecure-tls: true
    api-scheme: https
    funding:
      eth: 0.1
      gbzz: 2.0
    node-groups:
      bee-gw-1:
        mode: node
        bee-config: mainnet
        config: mainnet
        count: 1
      bee-gw-2:
        mode: node
        bee-config: mainnet
        config: mainnet
        count: 1
      bee-gw-3:
        mode: node
        bee-config: mainnet
        config: mainnet
        count: 1
      bee-gw-4:
        mode: node
        bee-config: mainnet
        config: mainnet
        count: 1

# node-groups defines node groups that can be registered in the cluster
# node-groups may inherit it's configuration from already defined node-group and override specific fields from it
node-groups:
  mainnet:
    _inherit: "default"
    persistence-enabled: true

# bee-configs defines Bee configuration that can be assigned to node-groups
# bee-configs may inherit it's configuration from already defined bee-config and override specific fields from it
bee-configs:
  mainnet:
    _inherit: "default"
    bootnodes: "/dnsaddr/mainnet.ethswarm.org"

# checks defines checks Beekeeper can execute against the cluster
# type filed allows defining same check with different names and options
#checks:
#  mainnet-smoke:
#    options:
#      content-size: 50000000
#      postage-amount: 2903040000 # 24000/5*60*60*24*7
#      postage-depth: 20
#      upload-groups:
#        - bee-gw-1
#        - bee-gw-3
#      download-groups:
#        - bee-gw-2
#        - bee-gw-4
#    timeout: 720h
#    type: smoke
#  mainnet-availability:
#    options:
#      refs:
#        - "2e70bb26d5b1f6f4a0961c42bb62e1066334a456c8835fb7ba34077b9d36859b"
#        - "d5fc0a2753360ddfb1825fb2d979031d4b620ddabd3e0aea69b685109ee357fe"
#        - "1cfd24178c67b708694b4ce4235d32e2a39d42813d2b09d1ef77eaa4c954931f"
#      retry-wait: 1m
#      retry-count: 3
#      next-iter-wait: 6h
#    timeout: 720h
#    type: longavailability
#  mainnet-durability:
#    options:
#      ref: 16c1437d310202ccea278cf1ea98cbd7f2830929d9e41b2a8fc9a1df74fa0d3f
#      concurrency: 20
#      max-attempts: 100
#    timeout: 720h
#    type: datadurability
#  mainnet-networkavailability:
#    options:
#      rnd-seed:
#      postage-amount: 50000000
#      postage-depth: 20
#      sleep-duration: 1h
#    timeout: 5m
#    type: networkavailability
