clusters:
  mainnet-dev-bee-perf:
    _inherit: ""
    name: bee
    namespace: dev-bee-perf
    disable-namespace: true
    api-domain: mainnet.internal
    api-domain-internal: dev-bee-perf.svc.godfather2.local:1633
    api-insecure-tls: true
    api-scheme: https
    funding:
      eth: 0.1
      gbzz: 2.0
    node-groups:
      bee-1:
        mode: node
        bee-config: mainnet-dev-bee-perf
        config: mainnet-dev-bee-perf
        count: 1
      bee-2:
        mode: node
        bee-config: mainnet-dev-bee-perf
        config: mainnet-dev-bee-perf
        count: 1
      bee-3:
        mode: node
        bee-config: mainnet-dev-bee-perf
        config: mainnet-dev-bee-perf
        count: 1
      bee-4:
        mode: node
        bee-config: mainnet-dev-bee-perf
        config: mainnet-dev-bee-perf
        count: 1

# node-groups defines node groups that can be registered in the cluster
# node-groups may inherit it's configuration from already defined node-group and override specific fields from it
node-groups:
  mainnet-dev-bee-perf:
    _inherit: "default"
    persistence-enabled: true

# bee-configs defines Bee configuration that can be assigned to node-groups
# bee-configs may inherit it's configuration from already defined bee-config and override specific fields from it
bee-configs:
  mainnet-dev-bee-perf:
    _inherit: "default"
    bootnodes: "/dnsaddr/mainnet.ethswarm.org"

# checks defines checks Beekeeper can execute against the cluster
# type filed allows defining same check with different names and options
# checks:
